# Generated by Django 4.1.2 on 2022-11-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_orderd_order_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
